#!/bin/bash
# Script accespts two numbers, and word add, multiply, subtract, or divide and print the result (using functions)
# Exit codes:
#	0: normal termination
#	1: invalid parameters
#	2: n1 is not an integer
#	3: n2 is not an integer
#	4: invalid oepration
#	5: Division by zero
function checkInt {
	VAL=$1
	TEMP="^[0-9]+$"
	if ! [[ $VAL =~ $TEMP ]]
	then
		echo "$VAL is not an integer"
		exit 1
	fi
}
if [ ! $# -eq 3 ]
then
	echo "Invalid paramters"
	echo "Usage: ./sc16 n1 n2 word"
	echo "n1 and n2 ar integers"
	echo "word must be add, subtract, mul, or divide"
	exit 1
fi
### Check for numbers
checkInt $1
checkInt $2
case "$3" in
	"add")
		RES=$[$1+$2]
		;;
	"subtract")
		RES=$[$1-$2]
		;;
	"mul")
		RES=$[$1*$2]
		;;
	"divide")
		if [ $2 -eq 0 ]
		then
				echo "Division by zero"
				exit 5
		fi
		RES=$[$1/$2]
		;;
	*)
		echo "Invalid operation"
		exit 4
		;;
esac
echo "Result = $RES"
exit 0
