#!/bin/bash
################## Script, asks you for add/delete/query
# Exit coeds
#	0:Normal termination

EMPINFOFILE="emp_info"
EMPDETAILSFILES="emp_details"

function checkID {
	ID=$1
	FNAME=$2
        LINE=$(grep "^$ID:" ${FNAME} | wc -l )
        return $LINE
}


function checkForEmployee {
	checkID $1 "${EMPINFOFILE}"
	return $?
}

function checkForDetails {
	checkID $1 "${EMPDETAILSFILES}"
        return $?
}

function addEmployee {
	################
	#	Add a new employee
	#	Return codes:
	#	0: Success
	#	1: Failed Employee is already exists
	#	2: Failed unable to write to the ${EMPINFOFILE}

	echo "Add an employee menu"
	echo -n "Enter employee ID : "
	read ID
	echo -n "Enter employee name : "
	read NAME
	echo -n "Enter employee email : "
	read EMAIL
	checkForEmployee ${ID}
	if [ $? -gt 0 ]
	then
		echo "Sorry, can not add the employee with ID ${ID}. It is already exists"
		return 1
	fi
	echo "${ID}:${NAME}:${EMAIL}" >> ${EMPINFOFILE}
	if [ $? -eq 0 ]
	then
		echo "Employee $ID added, and exit"
		return 0
	else
		echo "Sorry, could not add employee $ID, check for permissions"
		return 2
	fi

}

function deleteEmployee {
	######################## 
	#	Delete an existing employee
	#	Exist codes
	#	0:	Success
	#	1:	Employee is not exists
	#	2:	Employee has a details
	#	3:	Could not delete 

	echo "Delete an employee menu"
	echo -n "Enter required ID : "
	read ID
	checkForEmployee ${ID}
        if [ $? -eq 0 ]
	        then
	                echo "Sorry, can not delete the employee with ID ${ID}. It is not exists"
	                return 1
	        fi
	checkForDetails ${ID}
	if [ $? -gt 0 ]
                then
                        echo "Sorry, can not delete the employee with ID ${ID}. It has a details"
                        return 2
                fi
	sed -i "/^${ID}:/d" ${EMPINFOFILE}
	if [ $? -eq 0 ]
	then
		echo "User $ID has been deleted, exit"
		return 0
	else
		echo "Could not delete the user ${ID}, check for permissions"
		return 3
	fi

}

function queryEmployee {
	##################################
	#	Ask for an employee ID, and prints its info
	#	exit code
	#	0:	success
	#	1:	Employee is not found

	echo "Query for an employee meu"
	echo -n "Enter employee ID : "
	read ID
	checkForEmployee ${ID}
	if [ $? -eq 0 ]
                then
                       echo "Sorry, can not find employee with ID ${ID}. It is not exists"
                        return 1
                fi
	LINE=$(sed -n "/^${ID}:/p" ${EMPINFOFILE})
	NAME=$(echo $LINE| cut -d":" -f 2 )
	EMAIL=$(echo $LINE| cut -d":" -f 3 )
	echo "Employee name : ${NAME}"
	echo "Employee email : ${EMAIL}"
	return 0
}

function addEmployeeDetail {
	######################################
	#	Add the details for an existing employee
	#	exit codes
	#	0: Success
	#	1: not exists
	#	2: could not save
	echo "Add details for existing employee"
	echo -n "Enter Employee ID : "
	read ID
	checkForEmployee ${ID}
        if [ $? -eq 0 ]
                then
                      echo "Sorry, can not find employee with ID ${ID}. It is not exists"
                      return 1
                fi
	PRICE=0
	CO=1
	while [ $PRICE -ge 0 ]
	do
		echo -n "Enter price ${CO} : "
		read PRICE
		if [ $PRICE -ge 0 ]
		then
			D=$(date| sed -e 's/:/_/g' -e 's/ /_/g')
			echo "${ID}:${D}:${PRICE}" >> ${EMPDETAILSFILES}
			if [ $? -ne 0 ]
			then
				echo "Could not save"
				return 2
			fi
		fi
		CO=$[CO+1]
	done
		echo "Saved the employee $ID details"
		return 0
}

function deleteEmployeeDetails {
	##################################
	#	Delete a details for existing employee
	#	Exit codes
	#	0:	success
	#	1:	Employee is not found
	#	2:	No details for the employee
	#	3:	Could not delete from the file
	echo "Delete an existing employee details"
	echo -n "Enter employee ID : "
	read ID
	checkForEmployee ${ID}
        if [ $? -eq 0 ]
                then
                      echo "Sorry, can not find employee with ID ${ID}. It is not exists"
                      return 1
                fi
	checkForDetails ${ID}
        if [ $? -eq 0 ]
                then
                       echo "Sorry, there is no employee details for ${ID}."
                       return 2
                fi
	sed -i "/^${ID}:/d" ${EMPDETAILSFILES}
	if [ $? -eq 0 ]
	then
		echo "The details for ${ID} has been deleted"
		return 0
	else
		return 3
	
	fi
}


echo "Enter your selection"
options=("Add employee" "Delete an employee" "Query for an employee" "Add employee detail" "Delete an employee detail" "Query employee details" "Quit")
select opt in "${options[@]}"
do
case $opt in
	"Add employee")
			addEmployee
			;;
	"Delete an employee")	
			deleteEmployee
			;;
	"Query for an employee")
			queryEmployee
			;;
	"Add employee detail")
			addEmployeeDetail
			;;
	"Delete an employee detail")
			deleteEmployeeDetails
		;;
	"Query employee details")
		;;
	"Quit")
		echo "Thank you bye bye.."
		exit 0
		;;
	*)
		echo "Invalid selection"
esac
done
