#!/bin/bash
################## Script, asks you for add/delete/query
# Exit coeds
#	0:Normal termination

EMPINFOFILE="emp_info"
EMPDETAILSFILES="emp_details"

source sc21-emp-common
source sc21-emp-info
source sc21-emp-details

echo "Enter your selection"
options=("Add employee" "Delete an employee" "Query for an employee" "Add employee detail" "Delete an employee detail" "Query employee details" "Quit")
select opt in "${options[@]}"
do
case $opt in
	"Add employee")
			addEmployee
			;;
	"Delete an employee")	
			deleteEmployee
			;;
	"Query for an employee")
			queryEmployee
			;;
	"Add employee detail")
			addEmployeeDetail
			;;
	"Delete an employee detail")
			deleteEmployeeDetails
		;;
	"Query employee details")
		;;
	"Quit")
		echo "Thank you bye bye.."
		exit 0
		;;
	*)
		echo "Invalid selection"
esac
done
