#!/bin/bash
### Script accepts id,name,email, and insert it into file db_stinfo
###Exit codes:
##	0: normal
##	1: Invalid paramters
##	2: ID is not integer
##	3: ID is already exists
if [ ! $# -eq 3 ]
then
	echo "Invalid paramters"
	echo "Usage: ./sc12 id name email"
	echo "Note: If name contains spaces, include it into \""
	exit 1
fi
ID=$1
NAME=$2
EMAIL=$3
#### Check if ID is integer
temp1="^[0-9]+$"
if ! [[ $ID =~ $temp1 ]] 
then
	echo "Invalid ID format, must be integer"
	exit 2
fi
############## Must check for email address :-)
###################################################
## Check if the db_stinfo exists
if [ -f db_stinfo ]
then
	### Get lines contains the ID
	LINE=$(grep "^$ID:" db_stinfo|wc -l)
	if [ $LINE -eq 1 ]
	then
		echo "Invalid ID, it is already exists"
		exit 3
	fi
fi
#echo "$ID:$NAME:$EMAIL" >> db_stinfo

#echo "$ID is inserted"
#exit 0
declare -A DBSETTINGS



################ Only changes go here
DBSETTINGS["DBHOST"]="localhost"
DBSETTINGS["DBUSER"]="root"
DBSETTINGS["DBPASS"]="agh149agh"
DBSETTINGS["DBNAME"]="itidb"
DBSETTINGS["TABLENAME"]="STINFO"
#########################################################


mysql -u ${DBSETTINGS["DBUSER"]} -p${DBSETTINGS["DBPASS"]} -e "INSERT INTO ${DBSETTINGS["DBNAME"]}.${DBSETTINGS["TABLENAME"]}  VALUES ('$ID', '$NAME', '$EMAIL')"
#mysql -u ${DBSETTINGS["DBUSER"]} -p${DBSETTINGS["DBPASS"]} -e "select * from ${DBSETTINGS["DBNAME"]}.info"


